using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.EntityFrameworkCore;
using server.BusinessLogic;
using server.Data;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllers()
    .AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new System.Text.Json.Serialization.JsonStringEnumConverter());
    });
builder.Services.AddHttpClient();
builder.Services.AddOpenApi();
builder.Services.AddScoped<IAiService, AiService>();
builder.Services.AddScoped<IReviewScreeningService, ReviewScreeningService>();
builder.Services.AddSingleton<IRateLimiter, RateLimiter>();

builder.Services.AddDbContext<ReviewDbContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("Default") ?? "Host=localhost;Database=cdphysio;Username=postgres;Password=postgres"));

builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

var app = builder.Build();

// Ensure the reviews table exists in the database on startup.
// (EnsureCreated is not used because it skips schema creation when the database
// already exists, which is the case for hosted databases like Supabase.)
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<ReviewDbContext>();
    try
    {
        const string createTableSql = """
            CREATE TABLE IF NOT EXISTS "Reviews" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                "Name" text NOT NULL,
                "Rating" integer NOT NULL,
                "Text" text NOT NULL,
                "Service" text NULL,
                "Status" integer NOT NULL,
                "FlaggedReason" text NULL,
                "SubmittedAt" timestamptz NOT NULL,
                "ReviewedAt" timestamptz NULL,
                "ClientIpHash" text NULL,
                CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
            );
            CREATE INDEX IF NOT EXISTS "IX_Reviews_Status" ON "Reviews" ("Status");
            """;
        await db.Database.ExecuteSqlRawAsync(createTableSql);
    }
    catch (Exception ex)
    {
        var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Failed to initialize the reviews database.");
    }
}

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

app.UseForwardedHeaders(new ForwardedHeadersOptions
{
    ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto
});

app.UseExceptionHandler(errorApp =>
{
    errorApp.Run(async context =>
    {
        var error = context.Features.Get<Microsoft.AspNetCore.Diagnostics.IExceptionHandlerFeature>()?.Error;
        var logger = context.RequestServices.GetRequiredService<ILogger<Program>>();
        logger.LogError(error, "Unhandled exception while processing {Method} {Path}", context.Request.Method, context.Request.Path);

        context.Response.StatusCode = StatusCodes.Status500InternalServerError;
        context.Response.ContentType = "application/json";
        await context.Response.WriteAsJsonAsync(new { error = "Something went wrong. Please try again." });
    });
});

app.UseCors();
app.MapControllers();

app.Run();
