using Microsoft.EntityFrameworkCore;
using server.Data;

namespace server.Extensions;

public static class DatabaseExtensions
{
    public static async Task InitializeDatabaseAsync(this IHost app)
    {
        using var scope = app.Services.CreateScope();
        var services = scope.ServiceProvider;
        var logger = services.GetRequiredService<ILogger<Program>>();

        try
        {
            var db = services.GetRequiredService<ReviewDbContext>();
            const string createTableSql = """
                CREATE TABLE IF NOT EXISTS "Reviews" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "Name" text NOT NULL,
                    "Rating" integer NOT NULL,
                    "Text" text NOT NULL,
                    "Service" text NULL,
                    "Status" integer NOT NULL,
                    "FlaggedReason" text NULL,
                    "SubmittedAt" timestamptz NOT NULL,
                    "ReviewedAt" timestamptz NULL,
                    "ClientIpHash" text NULL,
                    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id")
                );
                CREATE INDEX IF NOT EXISTS "IX_Reviews_Status" ON "Reviews" ("Status");
                """;
            await db.Database.ExecuteSqlRawAsync(createTableSql);
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to initialize the reviews database schema.");
        }
    }
}
